### ISSUE TITLE
Typings could not be found

### ISSUE THREAD

**Issue by svelue** [SICKAG/collage#32]
When importing collage with typescript the index.d.ts could not be found due to an error in the package.json.

Could not find a declaration file for module '@collage/core'. 'c:/.../node_modules/@collage/core/dist/collage.es.js' implicitly has an 'any' type.
  There are types at 'c:/.../node_modules/@collage/core/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@collage/core' library may need to update its package.json or typings.

**Comment by svelue** [comment]
I created a pull request for this one.
https://github.com/SICKAG/collage/pull/33

**Comment by WanjaTschuorSICKAG** [comment]
Hi @svelue,

thank you for your contribution, I will test it as soon as possible.

**Comment by WanjaTschuorSICKAG** [comment]
Hi @svelue,

I reviewed, tested and merged your Pull Request. It will be part of our next release.
Before we publish the next release, we need to straighten some ts declarations.
I will keep this issue open as long as the work is ongoing.

**Comment by WanjaTschuorSICKAG** [comment]
This fix is part of the v0.2.10 release https://github.com/SICKAG/collage/releases/tag/v0.2.10
